name: deploy
# 触发 workflow 的事件
on:
  push:
    # 分支随意
    branches:
      - main
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
      #新建一个名为checkout_actions的步骤
      - name: checkout_actions
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v2
      #使用建一个名为setup-node的步骤
      - name: setup-node
        #使用setup-node@v1这个action
        uses: actions/setup-node@v1
        #指定某个action 可能需要输入的参数
        with:
          node-version: "14"
      - name: npm install and build
        #执行执行某个shell命令或脚本
        run: |
          npm install
          npm run build
          echo $secrets
      - name: rsync deployments
        # 部署
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: dist/
          # 部署路径
          remote_path: /www/com/baobiwang/blog/admin
          remote_host: 121.196.238.114
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
        # 环境变量
        env:
          email: aqv04720@163.com
